# Generated by Django 4.0.6 on 2023-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Author', models.CharField(blank=True, max_length=100, null=True)),
                ('Publicationyear', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
